added support for Fedora Linux (tested on ARM)

diff --git a/files/base/scripts/conf b/files/base/scripts/conf
--- a/files/base/scripts/conf
+++ b/files/base/scripts/conf
@@ -49,9 +49,6 @@ for arg in "$@"; do
                 arch+=("$i")
             fi
         ;;
-        "-no-download")
-            download=false
-        ;;
         *)
             error "'$arg' is not valid architecture or language"
             exit 1
@@ -80,24 +77,43 @@ for i in "${arch[@]}"; do
 
     compiler=NONE
     linker=NONE
-    # #   check the compiler
+
+    #   check for compiler and linker
     case "$lang" in
         c)
             for cc in $c_compiler_midnames; do
+                echo checking compiler for : "$(search_path "$(get_arch $i)$cc$(echo -n gcc)")"
+                echo checking linker for : "$(get_arch $i)$cc$(echo -n ld)"
                 if [ $compiler == NONE ]; then
-                    compiler="$(search_path "$(get_arch $i)$cc$(echo gcc)")"
+                    compiler="$(search_path "$(get_arch $i)$cc$(echo -n gcc)")"
                 fi
+
                 if [ $linker == NONE ]; then
-                    linker="$(search_path "$(get_arch $i)$cc$(echo ld)")"
+                    linker="$(search_path "$(get_arch $i)$cc$(echo -n ld)")"
                 fi
                 if [[ "$compiler" != NONE && "$linker" != NONE ]]; then
+                    note "using $(blue "$compiler") as C compiler"
+                    note "using $(blue "$linker") as linker"
                     break
                 fi
             done
         ;;
         rust)
             compiler="$(search_path cargo)"
-            linker="$(search_path "$(get_arch $i)-elf-ld")"
+
+            #linker="$(search_path "$(get_arch $i)-elf-ld")"
+
+            for cc in $c_compiler_midnames; do
+                if [ $linker == NONE ]; then
+                    linker="$(search_path "$(get_arch $i)$cc$(echo -n ld)")"
+                fi
+
+                if [ "$linker" != NONE ]; then
+                    note "using $(blue "$linker") as linker"
+                    break
+                fi
+
+            done
         ;;
     esac
     qemu="$(search_path "qemu-system-$(get_arch $i)")"
@@ -146,6 +162,33 @@ if [ ! -e $OS_CONFIG ]; then
     echo "version=0.0.1" >> $OS_CONFIG
     echo "release=BaseOS-v0.0.1" >> $OS_CONFIG
 fi
+
+#   TODO: copy .cargo/config-template.toml to .cargo/config.toml and change the value
+if [ ! -e "$PWD/kernel/.cargo/" ]; then
+    error "cargo specific configuration is missing ($(red "./kernel/.cargo/") directory is missing)"
+    note "please download $(yellow "kernel/.cargo/") directory from the BaseOS github repository"
+    echo "    https://github.com/LittleHobbitFrodo/BaseOS.git"
+    exit 2
+fi
+
+if [ ! -e "$PWD/kernel/.cargo/config-template.toml" ]; then
+    error "configuration template ($(red "./kernel/.cargo/config-template.toml")) is missing, please download it from the BaseOS github repository"
+    echo "  https://github.com/LittleHobbitFrodo/BaseOS.git"
+    exit 2
+fi
+
+cp "$PWD/kernel/.cargo/config-template.toml" "$PWD/kernel/.cargo/config.toml"
+if [ "$?" != 0 ]; then error "failed to copy cargo config template"; exit 2; fi
+
+sed -i "s|UTIL_LINKER_HERE|$PWD/kernel/symlink-linker-ld|g" "$PWD/kernel/.cargo/config.toml"
+
+if [ "$?" == 0 ]; then
+    note "note created cargo configuration file"
+else
+    error "failed to create cargo configuration file"
+    exit 2
+fi
+
 
 if [ "$all_tools_installed" != true ]; then
     warning "some development dependencies are missing, try running $(green "./util dep install") and then $(green "./util reconf")"
diff --git a/files/base/scripts/dep b/files/base/scripts/dep
--- a/files/base/scripts/dep
+++ b/files/base/scripts/dep
@@ -38,6 +38,12 @@ function check_package() {     #   returns if package should be added to the lis
     fi
 }
 
+#   check for no parameters
+if [ "$#" -eq 0 ]; then
+    error "please tell me what to do $(green "install or remove?")"
+    exit 1
+fi
+
 #   find except packages
 excluded=()
 if [ "$#" -gt 2 ]; then
@@ -59,11 +65,7 @@ fi
 packages=()
 
 
-if [ "$#" -eq 0 ]; then
-    error "please tell me what to do $(green "install or remove?")"
-    exit 1
-fi
-
+#   check if packages should be installed or removed
 case "$(echo $1 | tr '[:upper:]' '[:lower:]')" in
     remove)
         mode=remove
@@ -80,6 +82,46 @@ esac
 case $(check_package rustup rustup ) in
     OK)
         #   install rust
+        note "installing rustup"
+        warning "rustup installation will run script downloaded from the internet"
+
+        if [ $(ask "do you wish to proceed") == y ]; then
+            note "alright, the rustup installation will most likely need your attention"
+            for i in {5..0}; do
+                echo "starting in $i"
+                sleep 1
+            done
+            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
+
+            if [ "$?" != 0 ]; then
+                error "rustup installation failed"
+                exit 2
+            fi
+
+        else
+            note "skipping rustup installation"
+        fi
+
+        echo "$(red IMPORTANT): you may need to add rustup to your path (as listed above)"
+
+        note "rustup installation successfull"
+
+        local old_ifs="$IFS"
+        IFS=" "
+        for i in $arch; do
+            a="$(get_arch $i)"
+            note "installing target for $a"
+
+            rustup target add "$i-unknown-none"
+
+            if [ "$?" != 0 ]; then
+                error "failed to install target for $i"
+                exit 2
+            fi
+
+        done
+        IFS="$old_ifs"
+
     ;;
     NONE)
         note "$(blue rust) is already installed"
@@ -103,7 +145,7 @@ case "$(uname)" in
                     exit 2
                 fi
             else
-                error "Sorry, unable to work without Homebrew on mac :("
+                error 'Sorry, unable to work without Homebrew on mac :('
                 exit 2
             fi
         fi
@@ -148,11 +190,135 @@ case "$(uname)" in
         note "installing these packages: $(blue "${packages[@]}")"
         if [ $(ask "is this OK") == y ]; then
             brew $mode "${packages[@]}"
+
+            if [ "$?" != 0 ]; then
+                error "failed to install packages"
+                exit 2
+            fi
+
         else
             note "no packages were installed"
             exit
         fi
 
 
+    ;;
+
+    "Linux")
+        #   Gather distro information
+        source /etc/os-release
+
+
+        case $(echo "$NAME" | awk '{print $1}') in
+            "Fedora")
+
+                #   check whether to install compiler or only linker
+                case $lang in
+                    c)
+                        binutils_postfix="gcc"
+                    ;;
+                    rust)
+                        binutils_postfix="binutils"
+                    ;;
+                    *)
+                        error "language $lang is not supported by dep subcommand"
+                        exit 2
+                    ;;
+                esac
+
+                #   find linker/compiler
+                IFS=" "
+                for i in $arch; do
+                    i="$(get_arch $i)"
+
+                    case "$(check_package "qemu-system-$i" qemu)" in
+                        OK)
+                            packages="$packages qemu"
+                        ;;
+                        NONE)
+                            note "$(blue qemu) is already installed"
+                        ;;
+                        EXCLUDED)
+                            note "$(blue qemu) is excluded"
+                        ;;
+                    esac
+
+                    case "$(check_package "xorriso" xorriso)" in
+                        OK)
+                            packages="$packages xorriso"
+                        ;;
+                        NONE)
+                            note "$(blue xorriso) is already installed"
+                        ;;
+                        EXCLUDED)
+                            note "$(blue xorriso) is excluded"
+                        ;;
+                    esac
+
+                    case $(check_package "$i-linux-gnu-ld" "$binutils_postfix-$i-linux-gnu") in
+                        OK)
+                            packages=" $packages $binutils_postfix-$i-linux-gnu"
+                        ;;
+                        NONE)
+                            note "$(blue "$binutils_postfix-$i-linux-gnu") is already $mode_str"
+                        ;;
+                        EXCLUDED)
+                            note "$(blue "$binutils_postfix-$i-linux-gnu") is excluded"
+                        ;;
+                    esac
+                done
+
+                #   cc is needed for some parts of the kernel
+                case $(check_package "cc" "cc") in
+                    OK)
+                        packages="$packages rust-cc-devel"
+                    ;;
+                    NONE)
+                        note "$(blue cc) (rust-cc-devel) is already installed"
+                    ;;
+                    EXCLUDED)
+                        note "$(blue cc) (rust-cc-devel) is excluded"
+                    ;;
+                esac
+
+
+                if [ "${#packages[@]}" -eq 0 ]; then
+                    note "all packages are already $mode_str"
+                    exit
+                fi
+
+
+                note "installing these packages: $(blue "${packages[@]}")"
+                if [ $(ask "is this OK") == y ]; then
+                    note "using $(red sudo), the system may ask for password"
+                    sudo dnf $mode $packages
+
+                    if [ "$?" != 0 ]; then 
+                        error "failed to install packages"
+                        exit 2
+                    fi
+
+                else
+                    note "no packages were installed"
+                    exit
+                fi
+
+            ;;
+            "Ubuntu")
+                echo hello Ubuntu
+            ;;
+
+            *)
+                error "Sorry, your Linux distro does not seem to be supported"
+                exit 2
+            ;;
+        esac
+
+    ;;
+
+
+    *)
+        error "Sorry, your operating system does not seem to be supported"
+        exit 2
     ;;
 esac
