removed dependency to external linker | simplified few scripts | added kernel memory layout descriptor to ministd

diff --git a/files/base/scripts/dep b/files/base/scripts/dep
--- a/files/base/scripts/dep
+++ b/files/base/scripts/dep
@@ -2,12 +2,19 @@
 
 source "$PWD/files/base/scripts.conf"
 
+#   needed packages
+#       cargo
+#       emulator (qemu)
+#       xorriso
+
 
 function is_excluded() {
     old_ifs="$IFS"
     IFS=" "
     for i in "${excluded[@]}"; do
-        if [ "${excluded[$i]}" == "$1" ]; then
+        echo i: "$i"
+        if [ "$i" = "$1" ]; then 
+        #if [ "${excluded[$i]}" = "$1" ]; then
             IFS="$old_ifs"
             echo true
             return
@@ -19,7 +26,7 @@ function is_excluded() {
 
 function check_package() {     #   returns if package should be added to the list regardles operation mode
     #   $1 = program name to search
-    if [ $(is_excluded $2) == true ]; then
+    if [ "$(is_excluded $2)" == true ]; then
         echo EXCLUDED
         return
     fi
@@ -44,20 +51,12 @@ if [ "$#" -eq 0 ]; then
     exit 1
 fi
 
-#   find except packages
-excluded=()
-if [ "$#" -gt 2 ]; then
-    for arg in $@; do
-        if [[ "$arg" == "exclude" ]]; then
-            collect=1
-            echo found exclude
-            continue
-        fi
-        if [[ $collect -eq 1 ]]; then
-            echo "excluding: $arg"
-            excluded+="$arg"
-        fi
-    done
+#   check for no confirm
+no_confirm="NO"
+if [ "$#" -ge 2 ]; then
+    if [ "$2" == "-y" ]; then
+        no_confirm="YES"
+    fi
 fi
 
 
@@ -106,7 +105,7 @@ case $(check_package rustup rustup ) in
 
         note "rustup installation successfull"
 
-        local old_ifs="$IFS"
+        old_ifs="$IFS"
         IFS=" "
         for i in $arch; do
             a="$(get_arch $i)"
@@ -132,6 +131,10 @@ case $(check_package rustup rustup ) in
 esac
 
 
+#   pacnage manager command
+pm_command=NONE
+
+
 case "$(uname)" in
     Darwin)
         #   MacOS
@@ -150,58 +153,8 @@ case "$(uname)" in
             fi
         fi
 
-        #case $lang in
-        #    c)
-        #        binutils_postfix="gcc"
-        #    ;;
-        #    rust)
-                binutils_postfix="binutils"
-        #    ;;
-        #    *)
-        #        error "language $lang is not supported by dep subcommand"
-        #        exit 2
-        #    ;;
-        #esac
-
-        #   find linker/compiler
-        IFS=" "
-        for i in $arch; do
-            i="$(get_arch $i)"
-            case $(check_package "$i-elf-$binutils_postfix" "$i-elf-$binutils_postfix") in
-                OK) 
-                    packages+=("$i-elf-$binutils_postfix")
-                ;;
-                NONE)
-                    note "$(blue "$i-elf-$binutils_postfix") is already $mode_str"
-                ;;
-                EXCLUDED)
-                    note "$(blue "$i-elf-$binutils_postfix") is excluded"
-                ;;
-                esac
-        done
-
+        pm_command="brew $mode ${packages[@]}"
         
-
-        if [ "${#packages[@]}" -eq 0 ]; then
-            note "all packages are already $mode_str"
-            exit
-        fi
-
-        note "installing these packages: $(blue "${packages[@]}")"
-        if [ $(ask "is this OK") == y ]; then
-            brew $mode "${packages[@]}"
-
-            if [ "$?" != 0 ]; then
-                error "failed to install packages"
-                exit 2
-            fi
-
-        else
-            note "no packages were installed"
-            exit
-        fi
-
-
     ;;
 
     "Linux")
@@ -212,21 +165,7 @@ case "$(uname)" in
         case $(echo "$NAME" | awk '{print $1}') in
             "Fedora")
 
-                #   check whether to install compiler or only linker
-                # case $lang in
-                #     c)
-                #         binutils_postfix="gcc"
-                #     ;;
-                #     rust)
-                        binutils_postfix="binutils"
-                #     ;;
-                #     *)
-                #         error "language $lang is not supported by dep subcommand"
-                #         exit 2
-                #     ;;
-                # esac
-
-                #   find linker/compiler
+                #   find compiler
                 IFS=" "
                 for i in $arch; do
                     i="$(get_arch $i)"
@@ -242,31 +181,20 @@ case "$(uname)" in
                             note "$(blue qemu) is excluded"
                         ;;
                     esac
-
-                    case "$(check_package "xorriso" xorriso)" in
-                        OK)
-                            packages="$packages xorriso"
-                        ;;
-                        NONE)
-                            note "$(blue xorriso) is already installed"
-                        ;;
-                        EXCLUDED)
-                            note "$(blue xorriso) is excluded"
-                        ;;
-                    esac
-
-                    case $(check_package "$i-linux-gnu-ld" "$binutils_postfix-$i-linux-gnu") in
-                        OK)
-                            packages=" $packages $binutils_postfix-$i-linux-gnu"
-                        ;;
-                        NONE)
-                            note "$(blue "$binutils_postfix-$i-linux-gnu") is already $mode_str"
-                        ;;
-                        EXCLUDED)
-                            note "$(blue "$binutils_postfix-$i-linux-gnu") is excluded"
-                        ;;
-                    esac
                 done
+
+                #   check xorriso
+                case "$(check_package "xorriso" xorriso)" in
+                    OK)
+                        packages="$packages xorriso"
+                    ;;
+                    NONE)
+                        note "$(blue xorriso) is already installed"
+                    ;;
+                    EXCLUDED)
+                        note "$(blue xorriso) is excluded"
+                    ;;
+                esac
 
                 #   cc is needed for some parts of the kernel
                 case $(check_package "cc" "cc") in
@@ -281,33 +209,12 @@ case "$(uname)" in
                     ;;
                 esac
 
-
-                if [ "${#packages[@]}" -eq 0 ]; then
-                    note "all packages are already $mode_str"
-                    exit
-                fi
-
-
-                note "installing these packages: $(blue "${packages[@]}")"
-                if [ $(ask "is this OK") == y ]; then
-                    note "using $(red sudo), the system may ask for password"
-                    sudo dnf $mode $packages
-
-                    if [ "$?" != 0 ]; then 
-                        error "failed to install packages"
-                        exit 2
-                    fi
-
-                else
-                    note "no packages were installed"
-                    exit
+                pm_command="sudo dnf $mode ${packages[@]}"
+                if [ "$no_confirm" == "YES" ]; then
+                    pm_command="$pm_command -y"
                 fi
 
             ;;
-            "Ubuntu")
-                echo hello Ubuntu
-            ;;
-
             *)
                 error "Sorry, your Linux distro does not seem to be supported"
                 exit 2
@@ -322,3 +229,35 @@ case "$(uname)" in
         exit 2
     ;;
 esac
+
+
+
+#   install or remove packages
+if [ "${#packages[@]}" -eq 0 ]; then
+    note "all packages are already $mode_str"
+    exit
+fi
+
+if [ "$pm_command" == "NONE" ]; then
+    error "critical internal error: package manager command not set (NONE)"
+    exit 1
+fi
+
+if [ "$mode" == "install" ]; then
+    note "installing these packages: $(blue "${packages[@]}")"
+else
+    note "removing these packages: $(blue "${packages[@]}")"
+fi
+
+if [[ "$no_confirm" == "YES" || $(ask "is this OK") == y ]]; then
+    $pm_command
+
+    if [ "$?" != 0 ]; then
+        error "failed to install packages"
+        exit 2
+    fi
+
+else
+    note "no packages were installed"
+    exit
+fi
